Blockchain 129 fe apply for congressman feature
liberland/liberland_frontend pull request #112
Opened 2023-08-28 09:49 UTC by MichalLustykNeti

2023-08-28 10:01 UTC, kacperzuk-neti requested changes

2023-08-28 14:28 UTC, kacperzuk-neti requested changes

2023-08-28 14:28 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  return electionsCandidates.toHuman()
Not a blocker, but in the future only use `.toHuman()` when displaying stuff to a human. Definitely not in sagas/nodeRpcCall.js.

2023-08-28 14:28 UTC, kacperzuk-neti commented on src/redux/sagas/congress.js
> +    yield put(congressActions.applyForCongress.success());
We should update congress candidates on success.

2023-08-28 14:28 UTC, kacperzuk-neti commented on src/redux/reducers/congress.js
> +      congressActions.applyForCongress.success,
We shouldn't yet set loading to false on congressActions.applyForCongress.success.
On success, we should dispatch congressActions.getCongressCandidates.call to update list of candidates, and success of this action will set loading to false.

2023-08-28 14:28 UTC, kacperzuk-neti commented on src/redux/sagas/index.js
> +    congressSagas.getCongressCandidatesWatcher()
```suggestion
    congressSagas.getCongressCandidatesWatcher(),
```

2023-08-29 09:11 UTC, kacperzuk-neti approved these changes

2023-08-29 11:16 UTC, DorianSternVukotic approved these changes

2023-08-29 11:52 UTC, merged