BLOCKCHAIN-197 fixed routing tabs bug
liberland/liberland_frontend pull request #126
Opened 2023-09-14 11:51 UTC by MichalLustykNeti

2023-09-14 13:02 UTC, kacperzuk-neti requested changes

2023-09-14 13:02 UTC, kacperzuk-neti commented on src/router/index.js
> +    overview: '/home/registries/home',
double home looks weird
```suggestion
    overview: '/home/registries/overview',
```

2023-09-15 11:28 UTC, kacperzuk-neti approved these changes

2023-09-20 14:23 UTC, DorianSternVukotic approved these changes

2023-09-20 14:23 UTC, merged