BLOCKCHAIN-153 FE - make congress FE pretty
liberland/liberland_frontend pull request #137
Opened 2023-09-21 11:48 UTC by MichalLustykNeti

2023-09-22 14:18 UTC, kacperzuk-neti requested changes

2023-09-22 14:18 UTC, kacperzuk-neti commented on src/components/Congress/Treasury/index.js
> +          <h4>Spend period</h4>
Spend period is duplicated.

2023-09-22 14:26 UTC, kacperzuk-neti approved these changes

2023-09-23 09:35 UTC, DorianSternVukotic approved these changes

2023-09-23 09:36 UTC, merged