BLOCKCHAIN-212 FE - Voting for congressmen is missing loader
liberland/liberland_frontend pull request #146
Opened 2023-09-28 08:34 UTC by MichalLustykNeti

2023-09-28 11:43 UTC, kacperzuk-neti commented on src/redux/reducers/democracy.js
> +      loading: false,
Why not use the `gettingDemocracyInfo` that's already used by all other democracy actions for this purpose?

2023-10-03 12:28 UTC, kacperzuk-neti requested changes

2023-10-03 12:28 UTC, kacperzuk-neti commented on src/redux/reducers/democracy.js
> +      loading: true,
Why are we adding this?

2023-10-04 13:09 UTC, kacperzuk-neti approved these changes

2023-10-04 21:49 UTC, DorianSternVukotic approved these changes

2023-10-04 21:50 UTC, merged