BLOCKCHAIN-221 Adeded optional preimage creation if it do not exist
liberland/liberland_frontend pull request #148
Opened 2023-10-03 14:06 UTC by MichalLustykNeti

2023-10-03 14:25 UTC, kacperzuk-neti requested changes

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const existingPreimages = await api.query.preimage.preimageFor([addLaw.hash, addLaw.encodedLength])
```suggestion
  const existingPreimage = await api.query.preimage.preimageFor([addLaw.hash, addLaw.encodedLength])
```

But TBH I would even reduce it to just `preimage`.

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const existingPreimages = await api.query.preimage.preimageFor([extrinsicMethod.hash, extrinsicMethod.encodedLength])
```suggestion
  const existingPreimage = await api.query.preimage.preimageFor([extrinsicMethod.hash, extrinsicMethod.encodedLength])
```
But TBH I would reduce it to just `preimage`

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const extrinsicMethod = api.tx.liberlandLegislation.addLaw(
```suggestion
  const addLaw = api.tx.liberlandLegislation.addLaw(
```
`extrinsic` is the whole transaction. And is a bit too generic, given that we also operate on `democracy.propose*`, `preimage` and `utility.batchAll` calls

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +      proposeCall({ Legacy: extrinsicMethod.hash }, minDeposit),
Lets upgrade from `Legacy` to `Lookup`.

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  : proposeCall({ Legacy: extrinsicMethod.hash }, minDeposit);
Ditto.

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const existingPreimages = await api.query.preimage.preimageFor([repealLaw.hash, repealLaw.encodedLength])
```suggestion
  const existingPreimage = await api.query.preimage.preimageFor([repealLaw.hash, repealLaw.encodedLength])
```
But TBH I would reduce it to just preimage

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/redux/sagas/base.js
> +export function* democracyWatcher({ call, failure }, worker) {
Nooo, just use `blockchainWatcher` everywhere.

2023-10-03 14:25 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
>  const submitProposal = async (walletAddress, values, callback) => {
`callback` is now unused.

2023-10-04 10:16 UTC, kacperzuk-neti approved these changes

2023-10-04 21:54 UTC, DorianSternVukotic commented
Why

2023-10-05 08:43 UTC, kacperzuk-neti commented
Other than eslint fixes and refactoring to use `submitExtrinsic`, the main set of chances is this:

```
  const existingPreimage = await api.query.preimage.preimageFor([repealLaw.hash, repealLaw.encodedLength])

  const extrinsic = existingPreimages.isNone
  ? api.tx.utility.batchAll([
      api.tx.preimage.notePreimage(repealLaw.toHex()),
      api.tx.council.propose(threshold, proposal, proposal.length),
    ])
  : api.tx.council.propose(threshold, proposal, proposal.length);
  ```

If there already is a preimage for the exact call you want to make, `notePreimage` will fail saying that you can't have duplicates. So this PR detects that and skips `notePreimage` if we already have the preimage.
I assume this will rarely matter in production, unless Senate/Congress use their cancellation rights. It's mainly annoying during testing.

2023-10-05 08:51 UTC, kacperzuk-neti requested changes

2023-10-05 08:51 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const extrinsic = existingPreimages.isNone
```suggestion
  const extrinsic = existingPreimage.isNone
```

2023-10-05 08:51 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const extrinsic = existingPreimages.isNone
```suggestion
  const extrinsic = existingPreimage.isNone
```

2023-10-05 09:34 UTC, kacperzuk-neti approved these changes

2023-10-06 13:15 UTC, DorianSternVukotic commented
Ok, solve conflicts and merge when ready

2023-10-09 10:03 UTC, merged