BLOCKCHAIN-60 Replace Apollo with redux-saga + axios in frontend
liberland/liberland_frontend pull request #153
Opened 2023-10-13 10:42 UTC by MichalLustykNeti

2023-10-19 08:36 UTC, kacperzuk-neti requested changes

2023-10-19 08:36 UTC, kacperzuk-neti commented on src/api/explorer.js
> +        query Transfers($orderBy: [TransfersOrderBy!], $filter: TransferFilter) {
Either move this query out to a variable at the top of file or inline the `receiptsQuery` - I don't care either way, but let's be consistent.

2023-10-19 08:36 UTC, kacperzuk-neti commented on src/api/explorer.js
> +        query Merits($orderBy: [MeritsOrderBy!], $filter: MeritFilter) {
Either move this query out to a variable at the top of file or inline the `receiptsQuery` - I don't care either way, but let's be consistent.

2023-10-19 08:36 UTC, kacperzuk-neti commented
Fix commit msg.

2023-10-25 12:21 UTC, kacperzuk-neti requested changes

2023-10-25 12:21 UTC, kacperzuk-neti commented on src/api/explorer.js
> +      transfers(orderBy: $orderBy, filter: $filter) {
This fetches `LLD` transfers, not `LLM` transfers. LLM transfers are called `Merits` in GraphQL schema.

2023-11-08 23:57 UTC, DorianSternVukotic approved these changes

2023-11-09 12:47 UTC, merged