BLOCKCHAIN-228 - FE - for action buttons like "Blacklist" or "Repeal referendum" - detect if there's already an ongoing motion/referendum
liberland/liberland_frontend pull request #154
Opened 2023-10-17 14:39 UTC by MichalLustykNeti

![image](https://github.com/liberland/liberland_frontend/assets/133770876/a4778b46-9227-4074-9968-00c22acb5315)

2023-10-19 08:16 UTC, kacperzuk-neti requested changes
This issue is about all actions that create motions/referenda, not just blacklists. At the very least, its missing support for repealing legislation motions/referenda.

2023-10-19 08:16 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  console.log({proposalHash, referendumIndex })
```suggestion
```

2023-10-19 08:16 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +const loadProposalsBlacklistMotions = async (proposals, isReferendum) => {
Is this unused...?

2023-10-19 08:37 UTC, kacperzuk-neti commented
Fix commit msg.

2023-10-25 12:03 UTC, kacperzuk-neti requested changes

2023-10-25 12:03 UTC, kacperzuk-neti commented on src/components/Voting/Referendum/Items/ProposalItem/index.js
> +  blacklistMotion: PropTypes.string,
It should be required and contain `null` if there's no motion.

2023-10-25 12:03 UTC, kacperzuk-neti commented on src/components/Voting/Referendum/Items/ReferendumItem/index.js
> +  blacklistMotion: PropTypes.string,
It should be required and contain null if there's no motion.

2023-10-25 12:03 UTC, kacperzuk-neti commented on src/redux/actions/congress.js
> +  citizenProposeRepealLegislation,
This has nothing to do with congress. It should be either `democracy` or `legislation` actions (put it wherever we already have the action for proposing new legislation)

2023-10-26 11:53 UTC, MichalLustykNeti commented on src/api/nodeRpcCall.js
> +    .map(([_, exposure]) => {
from polka docs it may be reanemed

2023-10-26 11:55 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +    .map(([_, exposure]) => {
Docs for what? Can you link them?

2023-10-26 12:52 UTC, MichalLustykNeti commented on src/components/Modals/CitizenRepealLegislationModal.js
> +          { value: 'InternationalTreaty', display: 'International Treaty' },
I coppy that from CongressRepealLegislationFastTrackModal i fot that  we would like to use here only these laws. (i now added here Constitution also)

2023-10-27 08:12 UTC, MichalLustykNeti commented on src/api/nodeRpcCall.js
> +              .map(async (_, section) => {
Yes to get repeal law hash we do not need law content so se simply drop the content of it

2023-10-27 08:16 UTC, MichalLustykNeti commented on src/api/nodeRpcCall.js
> +  const existingPreimage = await api.query.preimage.preimageFor([referendumProposal.hash, referendumProposal.encodedLength])
referendumProposal is passed to func as argument
![image](https://github.com/liberland/liberland_frontend/assets/133770876/520c0e8a-a071-4844-a9f2-44a4e767526d)

2023-10-27 08:21 UTC, MichalLustykNeti commented on src/components/Congress/CitizenProposeRepealLegislationButton/index.js
> +  // requires parent to dispatch getMembers action
Yes it is it uses the same logic as RepealLegislationButton
![image](https://github.com/liberland/liberland_frontend/assets/133770876/84209180-6b2b-49d5-97d8-6a7b7dd8ad9c)

2023-10-27 08:21 UTC, MichalLustykNeti commented on src/components/Legislation/LegislationView/index.js
> +      { (repealReferendum || repealProposal) && <CitizenProposeRepealLegislationButton {...{ tier, id, section }} />}
True i changed it already

2023-10-30 14:44 UTC, closed without merging