BLOCKCHAIN-241 FE - Work on Company Registry UX
liberland/liberland_frontend pull request #158
Opened 2023-11-03 20:04 UTC by MichalLustykNeti

depends on BLOCKCHAIN-240/optimize-company-data-format

2023-11-06 12:51 UTC, kacperzuk-neti approved these changes

2023-11-06 15:44 UTC, kacperzuk-neti requested changes

2023-11-06 15:44 UTC, kacperzuk-neti commented on src/components/Registries/RegistriesCompanies/CompanyCRUD/index.js
> +function CompanyCRUD({ action }) {
Instead of taking `action` as prop, let's split this into two components - one for creating, one for editing.

2023-11-06 15:44 UTC, kacperzuk-neti commented on src/router/index.js
> +    companiesCRUD: {
Lets drop the `CRUD`, it's weird, especially when it's user visible.
Maybe something like this?
```
  companies: {
    overview: '/home/registries/companies',
    create: '/home/registries/companies/create',
    edit: '/home/registries/companies/edit/:companyId',
}
```

2023-11-07 13:18 UTC, kacperzuk-neti requested changes

2023-11-07 13:18 UTC, kacperzuk-neti commented on src/components/Registries/index.js
> +          /*
Something to cleanup?

2023-11-08 16:12 UTC, kacperzuk-neti requested changes

2023-11-08 16:12 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const { registryAllowedToEdit, ...restOfData } = companyData;
Let's refactor whatever is delivering this data. Action should already be dispatched with `editableByRegistrar` as a separate field.

2023-11-09 13:41 UTC, kacperzuk-neti commented on src/components/Registries/RegistriesCompanies/EditCompany/index.js
> +  }, [dispatch, registriesActions]);
```suggestion
  }, [dispatch, userWalletAddress]);
```
`registriesActions` is an imported module, it won't change and I believe eslint knows this and won't complain
`userWalletAddress` though must be in dependencies

2023-11-09 13:42 UTC, kacperzuk-neti commented on src/components/Registries/RegistriesCompanies/index.js
> +  }, [dispatch, registriesActions]);
```suggestion
  }, [dispatch, registriesActions]);
```
`registriesActions` is an imported module, it won't change and I believe eslint knows this and won't complain
`userWalletAddress` though must be in dependencies

(yea, I know it was already like that, but let's fix this as you've already touched it :P)

2023-11-10 17:28 UTC, DorianSternVukotic approved these changes

2023-11-10 19:14 UTC, merged