BLOCKCHAIN-412  FE Create contracts
liberland/liberland_frontend pull request #258
Opened 2024-03-11 13:03 UTC by MichalLustykNeti

Added create contract api call

2024-03-11 13:31 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +  const extrinsic = api.tx.contractsRegistry.createContract(data, parties);
Hmm.. how about we can compress the data (and decompress when reading it back)?

2024-03-19 04:30 UTC, SzymonZiebaNeti approved these changes

2024-03-19 16:28 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +      data = Buffer.from(pako.inflate(hexToU8a(hexData))).toString('utf-8');
```suggestion
      data = Buffer.from(pako.inflate(contractUnwrap.data.toU8a())).toString('utf-8');
```
Would this work?

2024-03-19 16:29 UTC, kacperzuk-neti requested changes

2024-03-19 16:29 UTC, kacperzuk-neti commented on src/api/nodeRpcCall.js
> +        data = Buffer.from(pako.inflate(hexToU8a(hexData))).toString('utf-8');
Never copy-paste such code. Extract it and deduplicate with `getSingleContract`.

2024-03-29 20:41 UTC, merged