BLOCKCHAIN-427 FE make companies its own menu entry, instead of being under registries
liberland/liberland_frontend pull request #271
Opened 2024-04-16 19:36 UTC by MichalLustykNeti

2024-04-16 23:42 UTC, DorianSternVukotic requested changes

2024-04-16 23:42 UTC, DorianSternVukotic commented on .env.dist
> +REACT_APP_IS_COMPANIES_DISCOURAGED=true
set to false

2024-04-16 23:46 UTC, DorianSternVukotic commented
Additional requirements.

Remove the 'encrypt field' checkboxes. Keep it as data, but the UI should not show it. False or null as default

Change 'append...' buttons text to 'add...' text

2024-04-18 14:39 UTC, SzymonZiebaNeti approved these changes

2024-04-19 20:26 UTC, merged