BLOCKCHAIN-443 FE senate
liberland/liberland_frontend pull request #295
Opened 2024-06-19 12:59 UTC by SzymonZiebaNeti

Wait until `https://github.com/liberland/liberland_substrate/pull/384` is merged

2024-07-15 17:34 UTC, DorianSternVukotic requested changes

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/api/nodeRpcCall.js
>    // we only want do download small preimages. fetching multi-megabyte setCode could be painful.
Maybe we should make a note and display to the user if there are lookupitems that are bigger, but just with a link to polkadotjs where he can see it. Is it possible to get something around the users if a call is purposefully big ?

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/api/nodeRpcCall.js
> +const getSenateMembers = async () => {
are senate members displayed anywhere? I couldnt find it

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/components/Congress/Motions/index.js
> +    return (<div>There is no any motion</div>);
Rename to There are no open motions

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/components/Modals/SpendModal.js
> +      remarkInfo: values.description || `${isCongress ? 'Congress' : 'Senate'} ${title}`,
Interface always shows congress, even when in senate tab

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/components/Modals/SpendModal.js
> +        {isCongress ? 'Congress' : 'Senate'}
interface always shows congress, even in senate tab

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/components/Senate/Motions/index.js
> +    return (<div>There is no any motion</div>);
rename to There are no open motions

2024-07-15 17:34 UTC, DorianSternVukotic commented on src/components/Senate/ScheduledCongressSpending/index.js
> +    return (<div>There is no any item</div>);
Rename to there are no open items

2024-07-15 17:35 UTC, DorianSternVukotic commented
Also fix

- sending asset as senate doesnt work, wrong amount error
- sending asest interface asks for amount LLD
- add remark to sending asset
- test congress functionalities if something broke

2024-07-17 08:20 UTC, kacperzuk-neti requested changes

2024-07-19 10:41 UTC, DorianSternVukotic commented on src/components/Modals/SendAssetModal.js
> +        {!isRemarkNeeded
OOF

We ll need to refactor how modal decides whether its sending your tokens or govt tokens

2024-07-19 10:42 UTC, merged