BLOCKCHAIN-516 FE enable usage without any wallet
liberland/liberland_frontend pull request #347
Opened 2024-11-06 09:59 UTC by SzymonZiebaNeti

2024-11-07 19:51 UTC, jindra12 commented on src/redux/sagas/base.js
> +      const isWallet = !e.stack.includes('Error: web3FromAddress: Unable to find injected');
This is very defensive and should be handled by reviewing the codebase and ensuring this doesn't happen to users. At the very least, this should be an "instanceof" check for error type if possible.

2024-11-07 19:52 UTC, jindra12 commented on src/redux/sagas/base.js
> +      const isWallet = !e.stack.includes('Error: web3FromAddress: Unable to find injected');
For instance, what if we upgrade polkadot library and  they change the error messages? This would stop working then.

2024-11-07 19:54 UTC, jindra12 commented on src/redux/sagas/base.js
> +      const isWallet = !e.stack.includes('Error: web3FromAddress: Unable to find injected');
If this is about accessing routes without an appropriate browser/wallet combination, I think react-router-dom library already has a way of validating a route, maybe try that?

2024-11-07 19:56 UTC, jindra12 commented on src/components/CheckExtenstionWalletProvider/index.js
>      dispatch(blockchainActions.setUserWallet.success(userBlockchainAdressStorage || wallets[0].address));
Can you also fix this please? This should be an useEffect not a part of render

2024-11-13 21:43 UTC, DorianSternVukotic commented on src/components/CheckExtenstionWalletProvider/index.js
> +          userBlockchainAdressStorage || wallets[0].address,
hmmm will have to see how this works with wallets that require you to connect again to the site

2024-11-13 21:43 UTC, DorianSternVukotic commented on src/components/Home/ChangeRouter.js
> +      }, 2000);
why is this on timeout, what is this doing?

2024-11-13 21:43 UTC, DorianSternVukotic commented on src/redux/sagas/blockchain.js
> +    setTimeout(updateWallets, 500);
why

2024-11-28 22:34 UTC, DorianSternVukotic commented
Rebase

White screen of death on clicking wallet - send lld without wallet
When signing transaction without wallet i get notification no wallet detected, you need to login and then it automatically redirects. Show a message to user, thats fine, but dont auto redirect, add a login and cancel button when signing without wallet

2024-12-04 23:32 UTC, DorianSternVukotic requested changes

2024-12-04 23:32 UTC, DorianSternVukotic commented on src/components/ErrorModal/index.js
> +                    Canel
canCel

2024-12-17 17:17 UTC, merged