Features/antd layout only
liberland/liberland_frontend pull request #358
Opened 2024-12-01 20:10 UTC by jindra12

ANTD layout in exchange and assets menus. Forms and most tables are still old school, but button layout has been updated

2024-12-04 10:02 UTC, SzymonZiebaNeti requested changes

2024-12-04 10:02 UTC, SzymonZiebaNeti commented on src/components/Wallet/WalletOverview/index.js
> +  const [filterTransactionsBy, setFilterTransactionsBy] = React.useState();
import { useState } from 'React'

2024-12-17 23:56 UTC, jindra12 commented on src/components/Documents/index.js
> +        component={() => <Profile className={styles.withoutMargin} />}
This has been in-app before my refactor, and the optimization of react that's coming up in the next PR has fixed this. Fixing it here would only add more conflicts down the road.

2024-12-18 08:22 UTC, SzymonZiebaNeti commented on src/components/Congress/CitizenProposeRepealLegislationButton/index.js
> +      <Button href="#">
We need this href here, also onClick is missing?
`<Button onClick={handleModalOpen}>`

2024-12-18 23:00 UTC, merged