Features/replace current components with antd
liberland/liberland_frontend pull request #371
Opened 2024-12-30 03:49 UTC by jindra12

Replace react-hook-form with ANTD components

    Replace tables with ANTD components

    Replace Card components with ANTD

    Replace Notifications with ANTD

2025-01-07 17:25 UTC, SzymonZiebaNeti requested changes

2025-01-07 17:25 UTC, SzymonZiebaNeti commented on src/components/Senate/ScheduledCongressSpending/index.js
> +  useLayoutEffect(() => {
This useLayoutEffect is needed here?

2025-01-07 17:25 UTC, SzymonZiebaNeti commented on src/components/Voting/Referendum/index.js
> +  useLayoutEffect(() => {
is this useLayoutEffect needed here?

2025-01-12 20:53 UTC, jindra12 commented on src/components/Companies/CompaniesCard/index.js
> +        }) || {}}
Done

2025-01-12 20:54 UTC, jindra12 commented on src/components/Voting/Referendum/index.js
> +  useLayoutEffect(() => {
Probably not, changed to useEffect

2025-01-12 21:15 UTC, jindra12 commented on src/components/CopyIconWithAddress/index.js
>  function CopyIconWithAddress({
Done, thanks!

2025-01-13 01:39 UTC, DorianSternVukotic requested changes

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Voting/CongressionalAssemble/index.js
> +            ) : <Alert type="info" message="No selected candidates" />,
doesnt show candidates even when candidates exist.

Candidates are current members, runnerups plus candidates, all in one list. Idk where the bug is, but just for context

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Voting/Referendum/index.js
> +                  Propose
button doesnt work, it just closes/opens the referendum menu, it should go to propose legislation menu

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Voting/Referendum/ProposalForms/AddLegislation/AddLegislation.js
>  function AddLegislation() {
Form doesnt work, adding legislation fails even before signing transaction

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Contracts/ContractItem/index.js
> +function ContractItem({
You removed the feature that contracts are collapsed by default, only showing a few lines, not entire contract in overview of all contracts. Reimplement pls

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Contracts/ContractItem/index.js
> +        <Button link onClick={() => handleClick(contractId)}>More</Button>
This should be regular link, no? Or clickable with middle mouse button

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/Voting/Referendum/ProposalForms/CongressAddLegislation/CongressAddLegislation.js
> +        label="Legislation index"
Double legislation id form item. Remove one

2025-01-13 01:39 UTC, DorianSternVukotic commented on src/components/WalletCongresSenate/Motion/index.js
> +          <Button
These buttons dont show probably because userIsMember is somehow borked

2025-01-13 19:00 UTC, jindra12 commented on src/components/Congress/DisplayOnlyLegislation/index.js
> +function DisplayOnlyLegislation({ section }) {
It displays readonly inputs, I'll rename it to ReadOnlyLegislation

2025-01-13 19:10 UTC, jindra12 commented on src/components/Profile/index.js
> +                disabled={!isUserEligibleForComplimentaryLLD || isLoading}
Done! :-)

2025-01-13 19:16 UTC, jindra12 commented on src/components/Modals/OnchainIdentityModal.js
> +        label="I want to change my identity"
Done!

2025-01-13 19:39 UTC, jindra12 commented on src/components/Nfts/Overview/index.js
> +      ) : <Alert type="info" message="No NFTs found" />}
Fixed thanks!

2025-01-13 20:04 UTC, jindra12 commented on src/components/Contracts/ContractItem/index.js
> +function ContractItem({
Added back thanks!

2025-01-13 20:11 UTC, jindra12 commented on src/components/Contracts/ContractItem/index.js
> +        <Button link onClick={() => handleClick(contractId)}>More</Button>
Fixed :-)

2025-01-13 20:12 UTC, jindra12 commented on src/components/Voting/Referendum/ProposalForms/CongressAddLegislation/CongressAddLegislation.js
> +        label="Legislation index"
Removed

2025-01-13 21:07 UTC, jindra12 commented on src/components/WalletCongresSenate/Motion/index.js
> +          <Button
Unborked

2025-01-13 21:44 UTC, jindra12 commented on src/components/Voting/Referendum/ProposalForms/AddLegislation/AddLegislation.js
>  function AddLegislation() {
Resolved by retesting

2025-01-13 22:16 UTC, DorianSternVukotic commented
Senate vote aye button doesnt show, though i can see vote nay

2025-01-13 22:18 UTC, jindra12 commented on src/components/InputComponents/InputSearchAddressName.js
> +              ? <CheckCircleFilled color="green" />
Done :-)

2025-01-13 22:23 UTC, jindra12 commented on src/components/Voting/CongressionalAssemble/index.js
> +            ) : <Alert type="info" message="No selected candidates" />,
Yeah I put in a the wrong list, fixed

2025-01-13 22:24 UTC, jindra12 commented on src/components/Nfts/ItemNft/index.js
> +                      collectionId={collectionId}
You are correct, removed

2025-01-13 22:29 UTC, jindra12 commented on src/components/Voting/Referendum/index.js
> +                  Propose
Replaced with navlink. Still closes menu for some unimaginable reason, but I'll fix that later

2025-01-14 22:54 UTC, merged